export const COLOR = {
  PRIMARY: '#FCDFB2',
  PRIMARY_DARK: '#F2CE98',
  PRIMARY_LIGHT: '#FDE7C4',
  SECONDARY: '#d8dae5',
  SECONDARY_DARK: '#c1c4d6',
  SECONDARY_LIGHT: '#edeff5',
  BACKGROUNG_DARK: '#F4F6FA',
  BACKGROUND_LIGHT: '#FAFBFF',
  TEXT_DARK: '#474d66',
}
